# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "📚 Notes"
  url = "notes/"
  identifier = "notes"
  weight = 1
  
[[main]]
  name = "2nd grade"
  url = "notes/#second-grade"
  parent = "notes"
  weight = 1

[[main]]
  name = "3rd grade"
  url = "notes/#third-grade"
  parent = "notes"
  weight = 2

[[main]]
  name = "4th grade"
  url = "notes/#fourth-grade"
  parent = "notes"
  weight = 3

[[main]]
  name = "1st Bacc"
  url = "notes/#first-bacc"
  parent = "notes"
  weight = 4

[[main]]
  name = "2nd Bach Physics"
  url = "notes/#second-bach-physics"
  parent = "notes"
  weight = 5
  
[[main]]
  name = "2nd Bach Chemistry"
  url = "notes/#second-bach-chemistry"
  parent = "notes"
  weight = 6  
  
[[main]]
  name = "🎓 EBAU resources"
  url = "ebau-resources/"
  identifier = "ebau-resources"
  weight = 2
  
[[main]]
  name = "☢️ Physics"
  url = "ebau-resources/#physics-exams"
  parent = "ebau-resources"
  weight = 1
  
[[main]]
  name = "⚗️ Chemistry"
  url = "ebau-resources/#chemistry-exams"
  parent = "ebau-resources"
  weight = 2  
  
[[main]]
  name = "💡 Tips"
  url = "ebau-resources/#tips"
  parent = "ebau-resources"
  weight = 3  

[[main]]
  name = "👐 Tutorials"
  url = "tutorials/"  
  identifier = "tutorials"
  weight = 3
  
[[main]]
  name = "$\\LaTeX$"
  parent = "tutorials"
  url = "tutorials/latex"
  weight = 1
  
[[main]]
  name = "Presentation of information"
  parent = "tutorials"
  url = "tutorials/presentation-information"
  weight = 2    

[[main]]
  name = "🔗 Links of interest"
  url = "links-interest/"  
  identifier = "links-interest"
  weight = 4
  
[[main]]
  name = "Online resources"
  url = "links-interest/#online-resources"
  parent = "links-interest"
  weight = 1
  
[[main]]
  name = "Friend pages"
  url = "links-interest/#friend-pages"
  parent = "links-interest"
  weight = 2

[[main]]
  name = "🗞️ News"
  url = "#news"
  identifier = "news"
  weight = 5

[[main]]
  name = "🐦 Twitter"
  url = "#news"
  parent = "news"
  weight = 1  
  
[[main]]
  name = "💬 Blog"
  url = "/post"
  parent = "news"
  weight = 2    

[[main]]
  name = "👨‍🔬 About me"
  url = "about-me/"
  identifier = "about-me"
  weight = 6
  
[[main]]
  name = "👨‍🔬 Interests and education"
  url = "about-me/"
  parent = "about-me"
  weight = 1

[[main]]
  name = "👣 Career path"
  url = "about-me/#career"
  parent = "about-me"
  weight = 2  
  
[[main]]
  name = "✈️ Research stays"
  url = "about-me/#stays"
  parent = "about-me"
  weight = 3    

[[main]]
  name = "✉️ Contact"
  url = "#contact"
  weight = 7

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
