# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Apuntes"
  url = "#apuntes"
  identifier = "apuntes"
  weight = 1
  
[[main]]
  name = "2º ESO"
  url = "#2ESO"
  parent = "apuntes"
  
[[main]]
  name = "3º ESO"
  url = "#3ESO"
  parent = "apuntes"
  
[[main]]
  name = "4º ESO"
  url = "#4ESO"
  parent = "apuntes"
  
[[main]]
  name = "1º Bach"
  url = "#1Bach"
  parent = "apuntes"
  
[[main]]
  name = "2º Bach"
  url = "#2Bach"
  parent = "apuntes"  

[[main]]
  name = "Blog"
  url = "#blog"
  weight = 2

[[main]]
  name = "Contacto"
  url = "#contacto"
  weight = 3

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
