# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "📚 Notes"
  url = "notes/"
  identifier = "notes"
  weight = 1
  
[[main]]
  name = "2nd grade"
  url = "notes/#second-grade"
  parent = "notes"
  weight = 1

[[main]]
  name = "3rd grade"
  url = "notes/#third-grade"
  parent = "notes"
  weight = 2

[[main]]
  name = "4th grade"
  url = "notes/#fourth-grade"
  parent = "notes"
  weight = 3

[[main]]
  name = "1º Bacc"
  url = "notes/#first-bacc"
  parent = "notes"
  weight = 4

[[main]]
  name = "2º Bach Physics"
  url = "notes/#second-bach-physics"
  parent = "notes"
  weight = 5
  
[[main]]
  name = "2º Bach Chemistry"
  url = "notes/#second-bach-chemistry"
  parent = "notes"
  weight = 6  
  
[[main]]
  name = "🎓 EBAU resources"
  url = "ebau-resources/"
  identifier = "ebau-resources"
  weight = 2
  
[[main]]
  name = "☢️ Physics"
  url = "ebau-resources/#examenes-fisica"
  parent = "ebau-resources"
  weight = 1
  
[[main]]
  name = "⚗️ Chemistry"
  url = "ebau-resources/#examenes-quimica"
  parent = "ebau-resources"
  weight = 2  
  
[[main]]
  name = "💡 Tips"
  url = "ebau-resources/#consejos"
  parent = "ebau-resources"
  weight = 3  

[[main]]
  name = "👐 Tutorials"
  url = "tutoriales/"  
  identifier = "tutoriales"
  weight = 3
  
[[main]]
  name = "$\\LaTeX$"
  parent = "tutoriales"
  url = "tutoriales/latex"
  weight = 1
  
[[main]]
  name = "Presentation of information"
  parent = "tutoriales"
  url = "tutoriales/presentacion-informacion"
  weight = 2    

[[main]]
  name = "🔗 Links of interest"
  url = "enlaces-interes/"  
  identifier = "enlaces-interes"
  weight = 4
  
[[main]]
  name = "Online resources"
  url = "enlaces-interes/#recursos-online"
  parent = "enlaces-interes"
  weight = 1
  
[[main]]
  name = "Friend pages"
  url = "enlaces-interes/#paginas-amigas"
  parent = "enlaces-interes"
  weight = 2

[[main]]
  name = "🗞️ News"
  url = "#novedades"
  identifier = "novedades"
  weight = 5

[[main]]
  name = "🐦 Twitter"
  url = "#novedades"
  parent = "novedades"
  weight = 1  
  
[[main]]
  name = "💬 Blog"
  url = "/post"
  parent = "novedades"
  weight = 2    

[[main]]
  name = "👨‍🔬 About me"
  url = "sobre-mi/"
  identifier = "sobre-mi"
  weight = 6
  
[[main]]
  name = "👨‍🔬 Interests and education"
  url = "sobre-mi/"
  parent = "sobre-mi"
  weight = 1

[[main]]
  name = "👣 Career path"
  url = "sobre-mi/#trayectoria"
  parent = "sobre-mi"
  weight = 2  
  
[[main]]
  name = "✈️ Research stays"
  url = "sobre-mi/#estancias"
  parent = "sobre-mi"
  weight = 3    

[[main]]
  name = "✉️ Contact"
  url = "#contacto"
  weight = 7

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
